%% constants for debugging
global CONSTANTS
CONSTANTS.DEBUG.SHOW = 0;
CONSTANTS.SIMULATION.SAVE_DB_FILE = false;

%% options for category: A, Ademo, EllipticalCylinder
% CONSTANTS.GEOMETRY.OBJECT_CATEGORY = 'Ademo'; 
% CONSTANTS.GEOMETRY.OBJECT_CATEGORY = 'A'; 

% CONSTANTS.GEOMETRY.OBJECT_CATEGORY = 'AdemoThick'; 
CONSTANTS.GEOMETRY.OBJECT_CATEGORY = 'AThick'; 
% CONSTANTS.GEOMETRY.OBJECT_CATEGORY = 'Asymmetric'; 

CONSTANTS.GEOMETRY.SAMPLING = 5;
CONSTANTS.SAVEIMAGES = 0;

%% directories
CONSTANTS.FINGER_TYPE = 'Finger-Beam';
CONSTANTS.DIR.SIMULATION = [PACKAGE_ROOT '/simulation/' CONSTANTS.FINGER_TYPE '/results/' CONSTANTS.GEOMETRY.OBJECT_CATEGORY num2str(CONSTANTS.GEOMETRY.SAMPLING) '/' ];
CONSTANTS.DIR.SIMULATION_ROOT = [PACKAGE_ROOT '/simulation/' CONSTANTS.FINGER_TYPE  '/'];
% CONSTANTS.DIR.ANSYS = '/home/jxu/software/ANSYS/ansys_inc/v172/ansys/bin/ansys172';
CONSTANTS.DIR.ANSYS = '/usr/ansys_inc/v172/ansys/bin/ansys172';
CONSTANTS.DIR.FEM_RESULTS = [PACKAGE_ROOT '/dataset/FEMsimulation/' CONSTANTS.FINGER_TYPE '/' CONSTANTS.GEOMETRY.OBJECT_CATEGORY '/'];

%% constants for contact
CONSTANTS.CONTACT.MU = 1;

%% constants for material properies
CONSTANTS.MATERIAL.YOUNGS_MODULUS = 2e3;
CONSTANTS.MATERIAL.NUXY = 0.03; % passions ratio
CONSTANTS.MATERIAL.DENSITY = 1350;
CONSTANTS.MATERIAL.MU = 0.2;

%% constants for FEM simulation
% CONSTANTS.SIMULATION.PRESSURE_ARRAY = [0.005,0.01,0.015];
% CONSTANTS.SIMULATION.FORCE_ARRAY = [2,5,7,10,13];% CONSTANTS.SIMULATION.FORCE_ARRAY = [2];
CONSTANTS.SIMULATION.FORCE_ARRAY = [13];% CONSTANTS.SIMULATION.FORCE_ARRAY = [2];

% Units: mPa and mm
% So the simulated forces are: [0.06    0.12    0.36    0.72   ...
%1.08    1.44    1.8    2.04    2.4]
% SHOULD also have different element size
% CONSTANTS.SIMULATION.PRESSURE_ARRAY = [0.001, 0.003, 0.006, 0.009, 0.012,0.015, 0.017, 0.02];
%% Thin-beam, festo
% symmetric contact, means dopple constact to prevent penetration. Use this
% if no solution.
% CONSTANTS.SIMULATION.SYMMETRIC_CONTACT = 0;

% CONSTANTS.SIMULATION.SENSOR_STIFFNESS = 1.5;
% CONSTANTS.SIMULATION.SENSOR_NUXY= 0.03;
% CONSTANTS.SIMULATION.SENSOR_DENSITY = 800;
% CONSTANTS.SIMULATION.SENSOR_MU = 0.333;
CONSTANTS.SIMULATION.SENSOR_STIFFNESS = 10;
CONSTANTS.SIMULATION.SENSOR_NUXY= 0.03;
CONSTANTS.SIMULATION.SENSOR_DENSITY = 1;
CONSTANTS.SIMULATION.SENSOR_MU = 0.333;

CONSTANTS.SIMULATION.SENSOR_WIDTH = 0.8;
CONSTANTS.SIMULATION.SENSOR_HEIGHT = 22;
CONSTANTS.SIMULATION.SENSOR_LENGTH = 50;

contact_area = (CONSTANTS.SIMULATION.SENSOR_HEIGHT * ...
    CONSTANTS.SIMULATION.SENSOR_LENGTH);

CONSTANTS.SIMULATION.PRESSURE_ARRAY = CONSTANTS.SIMULATION.FORCE_ARRAY ./ contact_area;


CONSTANTS.SIMULATION.RIM_THICKNESS_FACTOR = 10;
CONSTANTS.SIMULATION.MAX_STACKSIZE = '8192k';

CONSTANTS.SIMULATION.SQUEEZE_XAXIS = true;
CONSTANTS.SIMULATION.SQUEEZE_YAXIS = true;

% CONSTANTS.SIMULATION.ELEMENT_SZ_OBJECT = 5;
CONSTANTS.SIMULATION.ELEMENT_SZ_OBJECT = 3;

CONSTANTS.SIMULATION.ELEMENT_SZ_FINGER = 2;



%% constants for model generation
% when squeezing along x axis
CONSTANTS.MODEL.XAXIS.KEY_POINTS_PAIR_COEFF = {[1;1;1],[-1;1;1]};
CONSTANTS.MODEL.XAXIS.ROTATE_WORKSPACE = 'wprota,,90\n';
CONSTANTS.MODEL.XAXIS.MOVE_WORKSPACE_NEGATIVE = 'wpoffs,-%f\n';
CONSTANTS.MODEL.XAXIS.MOVE_WORKSPACE_POSITIVE= 'wpoffs,%f\n';
CONSTANTS.MODEL.XAXIS.SELECT_POSITIVE_HALF= 'ASEL,s,loc,x,1,';
CONSTANTS.MODEL.XAXIS.SELECT_NEGATIVE_HALF= 'ASEL,s,loc,x,-1,-';
CONSTANTS.MODEL.XAXIS.transToCenter  = [1,0,0];


CONSTANTS.MODEL.XAXIS.CONTACT1_AREA_FOAM_OBJ= '1004';
CONSTANTS.MODEL.XAXIS.CONTACT1_AREA_FOAM_STEEL= '2002';

CONSTANTS.MODEL.XAXIS.CONTACT2_AREA_FOAM_OBJ= '1002';

CONSTANTS.MODEL.XAXIS.CONTACT3_FOAM2= '2004';

CONSTANTS.MODEL.XAXIS.CONSTRAINTS1= 'DA,1002,uy,0\n';
CONSTANTS.MODEL.XAXIS.CONSTRAINTS2= 'DA,2004,uy,0\n';
CONSTANTS.MODEL.XAXIS.CONSTRAINTS3= 'DA,1002,uz,0\n';
CONSTANTS.MODEL.XAXIS.CONSTRAINTS4= 'DA,2004,uz,0\n';


CONSTANTS.MODEL.XAXIS.RECT_SENSOR_WIDTH = CONSTANTS.SIMULATION.SENSOR_WIDTH;
CONSTANTS.MODEL.XAXIS.RECT_SENSOR_HEIGHT= CONSTANTS.SIMULATION.SENSOR_HEIGHT;


% when squeezing along y axis
CONSTANTS.MODEL.YAXIS.KEY_POINTS_PAIR_COEFF = {[1;1;1],[1;-1;1]};
CONSTANTS.MODEL.YAXIS.ROTATE_WORKSPACE = 'wprota,,,-90\n';
CONSTANTS.MODEL.YAXIS.MOVE_WORKSPACE_NEGATIVE = 'wpoffs,,-%f\n';
CONSTANTS.MODEL.YAXIS.MOVE_WORKSPACE_POSITIVE = 'wpoffs,,%f\n';
CONSTANTS.MODEL.YAXIS.SELECT_POSITIVE_HALF= 'ASEL,s,loc,y,1,';
CONSTANTS.MODEL.YAXIS.SELECT_NEGATIVE_HALF= 'ASEL,s,loc,y,-1,-';
CONSTANTS.MODEL.YAXIS.transToCenter  = [0,1,0];



CONSTANTS.MODEL.YAXIS.CONTACT1_AREA_FOAM_OBJ= '1001';
CONSTANTS.MODEL.YAXIS.CONTACT1_AREA_FOAM_STEEL= '2003';

CONSTANTS.MODEL.YAXIS.CONTACT2_AREA_FOAM_OBJ = '1003';

CONSTANTS.MODEL.YAXIS.CONTACT3_FOAM2= '2001';

CONSTANTS.MODEL.YAXIS.CONSTRAINTS1= 'DA,1003,ux,0\n';
CONSTANTS.MODEL.YAXIS.CONSTRAINTS2= 'DA,2001,ux,0\n';
CONSTANTS.MODEL.YAXIS.CONSTRAINTS3= 'DA,1003,uz,0\n';
CONSTANTS.MODEL.YAXIS.CONSTRAINTS4= 'DA,2001,uz,0\n';



CONSTANTS.MODEL.YAXIS.RECT_SENSOR_WIDTH = CONSTANTS.SIMULATION.SENSOR_HEIGHT;
CONSTANTS.MODEL.YAXIS.RECT_SENSOR_HEIGHT= CONSTANTS.SIMULATION.SENSOR_WIDTH;
















