%% constants for debugging
global CONSTANTS
CONSTANTS.DEBUG.SHOW = 0;
CONSTANTS.SIMULATION.SAVE_DB_FILE = false;

%% options for category: A, Ademo, EllipticalCylinder
% CONSTANTS.GEOMETRY.OBJECT_CATEGORY = 'Ademo'; 
% CONSTANTS.GEOMETRY.OBJECT_CATEGORY = 'A'; 

% CONSTANTS.GEOMETRY.OBJECT_CATEGORY = 'AdemoThick'; 
CONSTANTS.GEOMETRY.OBJECT_CATEGORY = 'AThick'; 
% CONSTANTS.GEOMETRY.OBJECT_CATEGORY = 'Asymmetric'; 

CONSTANTS.GEOMETRY.SAMPLING = 5;
% CONSTANTS.GEOMETRY.SAMPLING = 10;
CONSTANTS.FILENAME = 1;
CONSTANTS.SAVEIMAGES = 0;

%% directories
CONSTANTS.FINGER_TYPE = 'Finger-Ellipsoid';
CONSTANTS.DIR.SIMULATION = [PACKAGE_ROOT '/simulation/' CONSTANTS.FINGER_TYPE '/results/' CONSTANTS.GEOMETRY.OBJECT_CATEGORY num2str(CONSTANTS.GEOMETRY.SAMPLING) '/' ];
CONSTANTS.DIR.SIMULATION_ROOT = [PACKAGE_ROOT '/simulation/' CONSTANTS.FINGER_TYPE  '/'];
% CONSTANTS.DIR.ANSYS = '/home/jxu/software/ANSYS/ansys_inc/v172/ansys/bin/ansys172';
CONSTANTS.DIR.ANSYS = '/usr/ansys_inc/v172/ansys/bin/ansys172';
CONSTANTS.DIR.FEM_RESULTS = [PACKAGE_ROOT '/dataset/FEMsimulation/' CONSTANTS.FINGER_TYPE '/' CONSTANTS.GEOMETRY.OBJECT_CATEGORY '/'];

%% constants for contact
CONSTANTS.CONTACT.MU = 1;

%% constants for material properies
CONSTANTS.MATERIAL.YOUNGS_MODULUS = 2e3;
CONSTANTS.MATERIAL.NUXY = 0.03; % passions ratio
CONSTANTS.MATERIAL.DENSITY = 1350;
CONSTANTS.MATERIAL.MU = 0.2;

%% constants for FEM simulation
% CONSTANTS.SIMULATION.PRESSURE_ARRAY = [0.001,0.002,0.005,0.01,0.015];
% CONSTANTS.SIMULATION.FORCE_ARRAY = [2, 5,10]; % make sure the force is the same
CONSTANTS.SIMULATION.FORCE_ARRAY = [2, 5,7,10,13]; % make sure the force is the same
% CONSTANTS.SIMULATION.FORCE_ARRAY = [13]; % make sure the force is the same

% CONSTANTS.SIMULATION.FORCE_ARRAY = [7]; % make sure the force is the same

% % CONSTANTS.SIMULATION.PRESSURE_ARRAY = [0.005,0.01,0.015];

% Units: mPa and mm
% So the simulated forces are: [0.06    0.12    0.36    0.72   ...
%1.08    1.44    1.8    2.04    2.4]
%% Human Finger 
% symmetric contact, means dopple constact to prevent penetration. Use this
% if no solution.
% CONSTANTS.SIMULATION.SYMMETRIC_CONTACT = 1;

CONSTANTS.SIMULATION.SENSOR_STIFFNESS = 0.2;
CONSTANTS.SIMULATION.SENSOR_NUXY= 0.5;
CONSTANTS.SIMULATION.SENSOR_DENSITY = 300;
CONSTANTS.SIMULATION.SENSOR_MU = 0.333;

CONSTANTS.SIMULATION.FINGER_THICK = 8;
CONSTANTS.SIMULATION.FINGER_LENGTH_FACTOR = 2.1538; % radius one of the half ellipsoid is FINGER_THICK * FINGER_LENGTH_FACTOR
CONSTANTS.SIMULATION.FINGER_WIDTH_FACTOR = 1.230;

contact_area = (pi*CONSTANTS.SIMULATION.FINGER_THICK ^2 * ...
    CONSTANTS.SIMULATION.FINGER_LENGTH_FACTOR *CONSTANTS.SIMULATION.FINGER_WIDTH_FACTOR);


CONSTANTS.SIMULATION.PRESSURE_ARRAY = CONSTANTS.SIMULATION.FORCE_ARRAY ./ contact_area;

CONSTANTS.SIMULATION.SENSOR_HEIGHT = ...
    CONSTANTS.SIMULATION.FINGER_THICK * CONSTANTS.SIMULATION.FINGER_WIDTH_FACTOR;

CONSTANTS.SIMULATION.RIM_THICKNESS_FACTOR = 10;
CONSTANTS.SIMULATION.MAX_STACKSIZE = '8192k';

CONSTANTS.SIMULATION.SQUEEZE_XAXIS = true;
CONSTANTS.SIMULATION.SQUEEZE_YAXIS = true;

% CONSTANTS.SIMULATION.ELEMENT_SZ_OBJECT =  5; % first use 5, if not converge, use 4
CONSTANTS.SIMULATION.ELEMENT_SZ_OBJECT =  3; % first use 5, if not converge, use 4

% CONSTANTS.SIMULATION.ELEMENT_SZ_FINGER = 3; % default finger size

%% constants for model generation
% when squeezing along x axis
CONSTANTS.MODEL.XAXIS.KEY_POINTS_PAIR_COEFF = {[1;1;1],[-1;1;1]};
CONSTANTS.MODEL.XAXIS.ROTATE_WORKSPACE = 'wprota,,,180\n';

% CONSTANTS.MODEL.XAXIS.MOVE_WORKSPACE_NEGATIVE = 'wpoffs,-%f\n';
% CONSTANTS.MODEL.XAXIS.MOVE_WORKSPACE_NEGATIVE = 'wpoffs,-%f,,-%f\n';
CONSTANTS.MODEL.XAXIS.MOVE_WORKSPACE_FINGER1 = 'wpoffs,-%f,,-%f\n';
CONSTANTS.MODEL.XAXIS.MOVE_WORKSPACE_FINGER2 = 'wpoffs,-%f,,%f\n';


CONSTANTS.MODEL.XAXIS.MOVE_WORKSPACE_POSITIVE= 'wpoffs,%f\n';
CONSTANTS.MODEL.XAXIS.SELECT_POSITIVE_HALF= 'ASEL,s,loc,x,1,';
CONSTANTS.MODEL.XAXIS.SELECT_NEGATIVE_HALF= 'ASEL,s,loc,x,-1,-';
CONSTANTS.MODEL.XAXIS.transToCenter  = [1,0,0];


CONSTANTS.MODEL.XAXIS.CONTACT1_AREA_FOAM_OBJ= '1004';
CONSTANTS.MODEL.XAXIS.CONTACT1_AREA_FOAM_STEEL= '2002';

CONSTANTS.MODEL.XAXIS.CONTACT2_AREA_FOAM_OBJ= '1002';

CONSTANTS.MODEL.XAXIS.CONTACT3_FOAM2= '2004';

CONSTANTS.MODEL.XAXIS.CONSTRAINTS= ...
    'DA,1002,uy,0\n DA,1005,uy,0\n DA,1008,uy,0\n DA,1011,uy,0\n DA,2002,uy,0\n DA,2005,uy,0\n DA,2008,uy,0\n DA,2011,uy,0\n ';



CONSTANTS.MODEL.XAXIS.VROTATE_FINGER1 ='vrotat,1000,,,,,,2000,2002,360\n';
CONSTANTS.MODEL.XAXIS.VSCALE_FINGER1 =['VLSCALE,1,4,,1,' num2str(CONSTANTS.SIMULATION.FINGER_LENGTH_FACTOR)...
    ',' num2str(CONSTANTS.SIMULATION.FINGER_WIDTH_FACTOR) ',0,0,1\n'];

CONSTANTS.MODEL.XAXIS.VROTATE_FINGER2 ='vrotat,2000,,,,,,3000,3002,360\n';
CONSTANTS.MODEL.XAXIS.VSCALE_FINGER2 =['VLSCALE,5,8,,1,' num2str(CONSTANTS.SIMULATION.FINGER_LENGTH_FACTOR)...
    ',' num2str(CONSTANTS.SIMULATION.FINGER_WIDTH_FACTOR) ',0,0,1\n'];

% when squeezing along y axis
CONSTANTS.MODEL.YAXIS.KEY_POINTS_PAIR_COEFF = {[1;1;1],[1;-1;1]};
CONSTANTS.MODEL.YAXIS.ROTATE_WORKSPACE = 'wprota,,180\n';

CONSTANTS.MODEL.YAXIS.MOVE_WORKSPACE_NEGATIVE = 'wpoffs,,-%f\n';
CONSTANTS.MODEL.YAXIS.MOVE_WORKSPACE_FINGER1 = 'wpoffs,,-%f,-%f\n';
CONSTANTS.MODEL.YAXIS.MOVE_WORKSPACE_FINGER2 = 'wpoffs,,-%f,%f\n';

CONSTANTS.MODEL.YAXIS.MOVE_WORKSPACE_POSITIVE = 'wpoffs,,%f\n';
CONSTANTS.MODEL.YAXIS.SELECT_POSITIVE_HALF= 'ASEL,s,loc,y,1,';
CONSTANTS.MODEL.YAXIS.SELECT_NEGATIVE_HALF= 'ASEL,s,loc,y,-1,-';
CONSTANTS.MODEL.YAXIS.transToCenter  = [0,1,0];



CONSTANTS.MODEL.YAXIS.CONTACT1_AREA_FOAM_OBJ= '1001';
CONSTANTS.MODEL.YAXIS.CONTACT1_AREA_FOAM_STEEL= '2003';

CONSTANTS.MODEL.YAXIS.CONTACT2_AREA_FOAM_OBJ = '1003';

CONSTANTS.MODEL.YAXIS.CONTACT3_FOAM2= '2001';

CONSTANTS.MODEL.YAXIS.CONSTRAINTS= ...
    'DA,1002,ux,0\n DA,1005,ux,0\n DA,1008,ux,0\n DA,1011,ux,0\n DA,2002,ux,0\n DA,2005,ux,0\n DA,2008,ux,0\n DA,2011,ux,0\n ';



CONSTANTS.MODEL.YAXIS.VROTATE_FINGER1 ='vrotat,1000,,,,,,2001,2002,360\n';
CONSTANTS.MODEL.YAXIS.VSCALE_FINGER1 =['VLSCALE,1,4,,' num2str(CONSTANTS.SIMULATION.FINGER_LENGTH_FACTOR)...
    ',1,' num2str(CONSTANTS.SIMULATION.FINGER_WIDTH_FACTOR) ',0,0,1\n'];

CONSTANTS.MODEL.YAXIS.VROTATE_FINGER2 ='vrotat,2000,,,,,,3001,3002,360\n';
CONSTANTS.MODEL.YAXIS.VSCALE_FINGER2 =['VLSCALE,5,8,,' num2str(CONSTANTS.SIMULATION.FINGER_LENGTH_FACTOR)...
    ',1,' num2str(CONSTANTS.SIMULATION.FINGER_WIDTH_FACTOR) ',0,0,1\n'];












